apiVersion: v1
kind: Service
metadata:
  name: digit-ai-system-service
spec:
  selector:
    app: digit-ai-system
  ports:
    - name: api
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: ui
      protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer
